### ISSUE TITLE
Can this Plugin be used for generation of packingslip

### ISSUE THREAD

**Issue by ninjacoder30** [pavelleonidov/magento2-webapi-pdfinvoice#1]
Can this Plugin be used for generation of packingslip -

Pleasse let me if  same plugin can be modified and used for packing slip/Shipping pdf fetch

**Comment by pavelleonidov** [comment]
Hi saigadekar,

yes and no. The given REST method of this plugin fetches the PDF stream of an invoice document whose template can customized with EaDesign's plugin (https://github.com/EaDesgin/magento2-pdf-generator2) and also depends on it. Generally, you could customize the the invoice template to look like a packing slip so that you have sort of a fake slip, but that also means that you roll out that version of an invoice document to your customers.

I guess you need Magento's standard packing slip feature to fetch by a REST call, but that would be a different approach with a different plugin - but also technically possible. Let me know if you have such a demand, then I would give it a try and create a new plugin with a different endpoint.

Best regards,

Pavel
